### ISSUE TITLE
Verify Readme for OData Sample. 

### ISSUE THREAD

**Issue by writemevenkat** [teiid/teiid-spring-boot#144]
I was able to get the OData Sample Spring Boot application up and running in a minute based on this Readme doc - https://github.com/teiid/teiid-spring-boot/blob/1.0.x/samples/odata/Readme.adoc. 

Used 1.2.0 teiid version with Spring Boot 2.2.1-RELEASE. 

I was not able to access the metadata using the following URL http://localhost:8080/$metadata. Later checking the test case I have updated the url as below and it worked. 

http://localhost:8080/odata/$metadata

**Comment by rareddy** [comment]
I fixed the url on the master branch now, thanks for pointing it out

**Comment by writemevenkat** [comment]
Thank you @rareddy
