### ISSUE TITLE
Maven Central?

### ISSUE THREAD

**Issue by dajester2013** [teiid/teiid-spring-boot#18]
The JBoss issue tracking shows that the issue concerning publishing to Maven Central is resolved and examples are given in this repository to use maven, but I cannot find this on any maven repo - is this still pre-release?

**Comment by rareddy** [comment]
@dajester2013 the code in the maven central now with version number 1.0.0

Sorry, I missed this before, for some reason, I am not getting the notifications.  let me know if you have any issues.
