### ISSUE TITLE
JDBC Query

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid-spring-boot#293]
If I have a spring boot app that uses external DDL vdb, can a SQL client query it using JDBC? Like wildfly deployment.

Thanks

**Comment by rareddy** [comment]
yes, you can. Here is an example using Spring Boot. https://github.com/teiid/teiid-spring-boot/blob/master/samples/vdb/src/test/java/org/teiid/spring/example/TestExample.java

In the above example, the VDB deployment application and the client are combined into a single application. If you want an external client, then provide a `teiid.jdbc-enable=true` in the `application.properties` file then it will open a port 31000 for external clients to connect. You can use same JDBC drivers as with the WildFly development and the same properties. It will not have authentication, but if that is needed then a Keycloak needs to be configured.
