### ISSUE TITLE
Information about support for Hibernate-Spatial

### ISSUE THREAD

**Issue by treiboll** [teiid/teiid-spring-boot#295]
Hi,

in our project we tried to use Teiid-Spring-Boot to connect to a PostGIS database. We want to use the so called [VDB-less Development](https://github.com/teiid/teiid-spring-boot/blob/master/docs/UserGuide.adoc#vdb-less-development). Therefore the hibernate spatial mapping for geometry-Types is needed. We tried different (datasource) configurations, but we couldn't get a running example.

Is the hibernate-spatial type mapping supported in Teiid-Spring-Boot and if so, can you provide us an example?

Hint: In our entities we use org.locationtech.jts.geom.Geometry (and subtypes) for the mapped fields.

**Comment by rareddy** [comment]
No, I have not added the support for the spatial types, if you want to submit a patch for it I am will be glad to review it.

**Comment by treiboll** [comment]
Thank you for your fast answer. I will think about that. I am not sure if I have enough knowledge about that but I will investigate some time on it.

**Comment by treiboll** [comment]
this is a cross post to https://issues.redhat.com/browse/TEIIDSB-227. In JIRA the discussion is going on.
