### ISSUE TITLE
Release 1.7.0 missing in Maven Central

### ISSUE THREAD

**Issue by ngschwendtner** [teiid/teiid-spring-boot#306]
Dear developers of the Teiid Spring Boot Framework,

I have read that version 1.7.0 has been released, but I cannot find it on maven central.
https://mvnrepository.com/artifact/org.teiid/teiid-spring-boot-starter/ 

Kind regards,
Niklas Gschwendtner

**Comment by rareddy** [comment]
I remember pushing to maven central, but yes I do not find either. I May have to do another 1.7.1

**Comment by ngschwendtner** [comment]
@rareddy I successfully pulled it from maven central, thank you very much! It was up pretty quick :D
