### ISSUE TITLE
Avoid use of `@ComponentScan` on auto-configuration

### ISSUE THREAD

**Issue by snicoll** [teiid/teiid-spring-boot#4]
The main auto-configuration has a `@ComponentScan` directive that doesn't sound right. When working with auto-configuration, things must be explicit, based on context and conditions. Scanning the whole package (even for convenience) is a bit fragile IMO. Perhaps you should `@Import` the thing that you need there?

**Comment by kylinsoong** [comment]
@snicoll thanks, I agree the scope of `@ComponentScan` is too large, the initial add it for make sure the configuration like [1] can be auto loaded.

I have removed @ComponentScan, workaround test.

[1] https://github.com/teiid/teiid-spring-boot/blob/master/teiid-spring-boot-starter-test/src/test/java/org/jboss/teiid/springboot/TestConfiguration.java
