### ISSUE TITLE
`@ConfigurationProperties` must have a root prefix

### ISSUE THREAD

**Issue by snicoll** [teiid/teiid-spring-boot#5]
`TeiidConnectorConfiguration` should have a root prefix for the `@ConfigurationProperties`.  Such POJO bound to the environment are usually called properties object so I'd rather call that `TeiidConnectorProperties`. 

Also, this shouldn't be a `@Configuration` (that thing does not and should not provide bean definitions). If you want it to be processed, add `@EnableConfigurationPropertiers(TeiidConnectorProperties.class` on your auto-configuration as described in the documentation.

**Comment by kylinsoong** [comment]
Thanks suggestions, I have fixed it.
